# Config file for the vLLM runner

model:
  id: "qwen2_5-VL-3B-Instruct"
  user_id: "user_id"
  app_id: "app_id"
  model_type_id: "multimodal-to-text"

build_info:
  python_version: "3.12"

inference_compute_info:
  cpu_limit: "1"
  cpu_memory: "14Gi"
  num_accelerators: 1
  accelerator_type: ["NVIDIA-*"]
  accelerator_memory: "18Gi"

checkpoints:
  type: "huggingface"
  repo_id: "Qwen/Qwen2.5-VL-3B-Instruct"
  when: "runtime"
