model:
  id: github-mcp-server
  app_id: app_id
  user_id: user_id
  model_type_id: text-to-text
build_info:
  python_version: '3.11'
  node_version: '20.11.1'
inference_compute_info:
  cpu_limit: 1000m
  cpu_memory: 1Gi
  num_accelerators: 0
secrets:
  - id: "github_personal_access_token"
    type: "env"
    env_var: "GITHUB_PERSONAL_ACCESS_TOKEN"
    description: "GitHub personal access token"
mcp_server:
  command: "npx"
  args: ["-y", "@modelcontextprotocol/server-github" ]