model: 
  id: "flux_1-schnell"
  user_id: 
  app_id: image-model
  model_type_id: "text-to-image"

build_info:
  python_version: "3.11"
  platform: "linux/amd64,linux/arm64"

inference_compute_info:
  cpu_limit: "3"
  cpu_memory: "18Gi"
  num_accelerators: 1
  accelerator_type: ["NVIDIA-*"]
  accelerator_memory: "44Gi"

checkpoints:
  type: huggingface
  repo_id: black-forest-labs/FLUX.1-schnell
  hf_token: 
  when: runtime