build_info:
  python_version: '3.12'
inference_compute_info:
  cpu_limit: '1'
  cpu_memory: 500Mi
  num_accelerators: 0
model:
  app_id: agentic-model
  id: gpt-5_1
  model_type_id: multimodal-to-text
  user_id: clarifai
