model:
  id: DeepSeek-OCR
  user_id: YOUR_USER_ID
  app_id: YOUR_APP_ID
  model_type_id: multimodal-to-text
build_info:
  python_version: '3.11'
inference_compute_info:
  cpu_limit: '3'
  cpu_memory: 18Gi
  num_accelerators: 1
  accelerator_type:
  - NVIDIA-L40S
  - NVIDIA-A100
  accelerator_memory: 42Gi