model:
  id: "phi-35-mini-instruct"
  user_id: "arman"
  app_id: "llm"
  model_type_id: "text-to-text"

build_info:
  python_version: "3.11"

inference_compute_info:
  cpu_limit: "2"
  cpu_memory: "16Gi"
  num_accelerators: 1
  accelerator_type: ["NVIDIA-A10G", "NVIDIA-T4", "NVIDIA-L4"]
  accelerator_memory: "12Gi"

checkpoints:
  type: "huggingface"
  repo_id: "microsoft/Phi-3.5-mini-instruct"
  when: "runtime"
